### PR TITLE
Dependency updates, lock down runit to 1.5.x

### PR DESCRIPTION
**Pull request by ARentz07**
Addresses issues found from internal code review as well as updates for dependencies. 

There was an issue found with runit (https://github.com/cerner/ops_tcpdump_handler/issues/1) causing kitchen tests to fail, and this has been resolved by locking runit down as well.

### CODE REVIEW

**Comment by david-crowder** [comment]
+1

**Comment by david-crowder** [comment]
+1

**Comment by ARentz07** [comment]
Note, we will probably want to squash these down - just left them separate for ease of reviewing.

**Comment by david-crowder** [comment]
Agreed regarding the squashing. Could you add yourself to the CONTRIBUTORS.md and squash down the commits? Once this gets merged I will log a follow up to #1 to relax the constraint on runit since this is intended to be consumed alongside cookbooks which may have their own constraints on runit. We will just need to figure out why it is breaking on latest.

@sambao21 would you mind taking a look at this as well? The majority of the changes have already been reviewed, they just got missed in the transfer to the new repo.

**Comment by nimeshsubramanian** [comment]
+1

**Comment by ARentz07** [comment]
Squashed commits down to two and kept David's commits separate from mine.

**Comment by ARentz07** [comment]
Hmm, do we need to add a changelog entry for this?

**Comment by david-crowder** [comment]
Yes, I was going to do that in the merge, but if you want do to it and squash again go for it :)

**Comment by ARentz07** [comment]
Hmm, if you could do it, might be easier, since we don't have any milestones, etc. to which to link. I would rather the owning team establish conventions for that type of thing. 
(I was referring to this for reference: https://github.com/cerner/cerner_kafka/blob/master/CHANGELOG.md)

**Pull request merged**
